site_name: Declarai
nav:
- Declarai: index.md
- Tutorial - User Guide: tutorial/index.md
theme:
    feaures:
      - tabs
      - content.tooltips
      - content.code.copy
      - content.code.annotate
    name: material
    icon:
      logo: material/cloud
extra_css:
- css/extra.css
- css/termynal.css
extra_javascript:
- js/termynal.js
- js/custom.js
repo_url: https://github.com/vendi-ai/declarai
repo_name: vendi-ai/declarai
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences