site_name: Declarai
nav:
- Declarai: index.md
- Tutorial - User Guide:
  - tutorial/index.md
  - First Steps: tutorial/first_steps.md
- Changelog: changelog.md

theme:
    features:
      - tabs
      - content.tooltips
      - content.code.copy
      - content.code.annotate
    name: material
    icon:
      logo: material/cloud
extra_css:
- css/extra.css
- css/termynal.css
extra_javascript:
- js/termynal.js
- js/custom.js
repo_url: https://github.com/vendi-ai/declarai
repo_name: vendi-ai/declarai
markdown_extensions:
- attr_list
- md_in_html
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

